#!/usr/bin/env python

import os
import whisper

os.makedirs("whisper-cache", exist_ok=True)

models = ["large","base"]

for model in models:
    print(f"Downloading {model}...")
    whisper._download(whisper._MODELS[model], "whisper-cache", in_memory=False)
