#!/usr/bin/env python

import os
import whisper
import requests

def download_file(url, destination_folder, name):
    # Get the filename from the URL
    filename = name
    # Create the destination path
    destination_path = f"{destination_folder}/{filename}"

    # Make a GET request to fetch the raw content of the file
    response = requests.get(url, stream=True)

    # Raise an exception if the request was unsuccessful
    response.raise_for_status()

    # Write the content to the file in chunks
    with open(destination_path, "wb") as file:
        for chunk in response.iter_content(chunk_size=8192):
            file.write(chunk)

os.makedirs("whisper-cache", exist_ok=True)

# Destination folder
destination_folder = "whisper-cache"

models = ["large","base"]

for model in models:
    print(f"Downloading {model}...")
    whisper._download(whisper._MODELS[model], "whisper-cache", in_memory=False)
